# Generated by Django 2.2.2 on 2020-02-18 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item_food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='img/standart.png', null=True, upload_to='img', verbose_name='аватарка')),
                ('name', models.CharField(default='', max_length=100, verbose_name='имя')),
                ('choices', models.CharField(choices=[('burger', 'burger'), ('roll', 'roll'), ('lanch', 'lanch'), ('salat', 'salat'), ('drinks', 'drinks')], max_length=9, verbose_name='категория')),
                ('price', models.IntegerField(verbose_name='цена')),
                ('about_item', models.CharField(default='', max_length=300, verbose_name='о товаре')),
                ('kkal', models.IntegerField(verbose_name='цена')),
                ('fats', models.IntegerField(verbose_name='жиры')),
                ('proteins', models.IntegerField(verbose_name='белки')),
                ('carbohydrates', models.IntegerField(verbose_name='углеводы')),
            ],
            options={
                'db_table': 'food',
            },
        ),
        migrations.CreateModel(
            name='Composition_food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(default='', max_length=100, verbose_name='компонент')),
                ('item_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_menu.Item_food')),
            ],
            options={
                'db_table': 'Composition_food',
            },
        ),
    ]
